name: 'BuildAndDeploy'

on:
    push:
        branches:
        - master
    pull_request:
        branches:
        - master

env:
  solution_name: 'Nibo.DevOpsChallenge.sln'
  rg_name: 'RG_LABADC'
  webapp_name: 'webapplabadc'
  package_path: '\publishWebSite'

jobs:
    build:
        name: 'Nibo.DevOpsChallenge'
        runs-on: windows-latest

        defaults:
            run:
                working-directory: DevOpsChallenge

        steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Setup MSBuild path
          uses: microsoft/setup-msbuild@v1.0.1
          with:
            vs-version: "[16.4,16.9)"
        
        - name: Setup NuGet
          uses: NuGet/setup-nuget@v1.0.2
        
        - name: Restore NuGet packages
          run: nuget restore ${{ env.solution_name }}

        - name: Build
          run: msbuild ${{ env.solution_name }} /p:Configuration=Release

        - name: Publish to folder
          run: msbuild ${{ env.solution_name }} /p:DeployOnBuild=true /p:OutDir=${{ env.package_path }} /p:Configuration=release

        - name: Deploy to Azure WebApp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.webapp_name }}
            package: '${{ env.package_path }}\_PublishedWebsites\Nibo.DevOpsChallenge'
            publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}

        - name: Publish artifacts
          uses: actions/upload-artifact@v1.0.0
          with:
            name: webapp
            path: '${{ env.package_path }}'