name: 'Infrastructure'

on:
    push:
        branches:
        - master
    pull_request:
        branches:
        - master

env:
  rg_name: 'RG_LABADC'
  webapp_name: 'webapplabadc' 

jobs:
    Infrastructure:
      name: 'terraform'
      runs-on: ubuntu-latest

      defaults:
          run:
              shell: bash
              working-directory: Infrastructure

      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.terraform_token }}

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:
          tokenPrefix: '##'
          tokenSuffix: '##'
          files: '["**/*.auto.tfvars"]'
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          resourcegroup_name: ${{ env.rg_name }}
          appservice_name: ${{ env.webapp_name }}

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve